### ISSUE TITLE
change script to not remove global config

### ISSUE THREAD

**Issue by joshuavial** [enspiral-dev-academy/git-iam#9]
The script is blatting the global user config which seems like pretty poor behaviour to me, but it was intentionaly introduced in https://github.com/enspiral-dev-academy/git-iam/commit/8c0f2ed2cd960f25d107a642f73dfb986154423f

**Comment by don-smith** [comment]
It does this because it is only intended to be installed on shared computers where the global config should never be used (because it isn't likely to represent the current pair). Global configs were causing problems like people not getting credit for their commits and they don't make sense on shared computers. git-iam doesn't make sense (and shouldn't be installed) on an individual's computer - only shared ones.

**Comment by don-smith** [comment]
See the v0.2.0 notes in the readme to understand why it was added.

**Comment by meetjohngray** [comment]
Resolved. @rohan-fowlerharper created a patch that allows this to be flagged on and off when installed
